# Generated by Django 3.2.4 on 2021-10-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('coat', models.CharField(blank=True, max_length=100)),
                ('owner', models.CharField(blank=True, max_length=100)),
                ('yearofbirth', models.CharField(blank=True, max_length=4)),
                ('ifce', models.CharField(blank=True, max_length=9)),
                ('ueln', models.CharField(blank=True, max_length=15)),
                ('sire', models.CharField(blank=True, max_length=300)),
                ('siresire', models.CharField(blank=True, max_length=300)),
                ('siredam', models.CharField(blank=True, max_length=300)),
                ('dam', models.CharField(blank=True, max_length=300)),
                ('damsire', models.CharField(blank=True, max_length=300)),
                ('damdam', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
