# Generated by Django 3.2.4 on 2021-10-26 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0002_auto_20211025_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='notes',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='horse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
