# Generated by Django 3.2.4 on 2021-10-26 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0003_auto_20211026_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='T/G', max_length=200)),
                ('date', models.CharField(default='T/G', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaxhorse', to='horses.horse')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaxowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
