# Generated by Django 3.2.4 on 2021-10-27 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0004_vaccine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='name',
            new_name='kind',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='horse',
            name='tests',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='next',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='horse',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(default='37.5')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temphorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repertory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=12)),
                ('lastname', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job', models.CharField(choices=[('farrier', 'Maréchal'), ('vet', 'Vétérinaire'), ('osteo', 'Osthéopathe'), ('inseminator', 'Inséminateur'), ('other', 'Autre'), ('rider', 'Cavalier professionnel'), ('provider', 'Fournisseur'), ('acup', 'Acupuncteur'), ('masseur', 'Masseur'), ('breeder', 'Eleveur'), ('teacher', 'Moniteur'), ('dentist', 'Dentiste')], default='other', max_length=11)),
                ('nb', models.CharField(blank=True, max_length=13)),
                ('tab', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Osteopathy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(blank=True, max_length=2000)),
                ('date', models.CharField(default='Unknown', max_length=10)),
                ('reeducation', models.CharField(blank=True, max_length=1000)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osthorse', to='horses.horse')),
                ('osteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposteo', to='horses.repertory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('molecule', models.CharField(blank=True, max_length=50)),
                ('quantity', models.IntegerField(blank=True)),
                ('dateend', models.CharField(default='Unknown', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=10)),
                ('prescription', models.CharField(blank=True, max_length=2000)),
                ('notes', models.CharField(blank=True, max_length=3000)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inchorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Heats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.CharField(default='Unknown', max_length=10)),
                ('dateend', models.CharField(default='Unknown', max_length=10)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heathorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.CharField(default='Unknown', max_length=10)),
                ('dateend', models.CharField(default='Unknown', max_length=10)),
                ('echo1', models.CharField(default='Not done yet', max_length=100)),
                ('echo2', models.CharField(default='Not done yet', max_length=100)),
                ('echo3', models.CharField(default='Not done yet', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=4000)),
                ('realend', models.CharField(blank=True, max_length=10)),
                ('foal', models.CharField(blank=True, max_length=500)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gesthorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestowner', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repgest', to='horses.repertory')),
            ],
        ),
        migrations.CreateModel(
            name='Dewormer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=30)),
                ('molecule', models.CharField(blank=True, max_length=50)),
                ('date', models.CharField(blank=True, max_length=10)),
                ('nextname', models.CharField(blank=True, max_length=30)),
                ('nextdate', models.CharField(blank=True, max_length=13)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewhorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dentistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostic', models.CharField(blank=True, max_length=2000)),
                ('date', models.CharField(default='Unknown', max_length=10)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repdent', to='horses.repertory')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denthorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider', models.CharField(blank=True, max_length=40)),
                ('discipline', models.CharField(blank=True, max_length=10)),
                ('division', models.CharField(blank=True, max_length=20)),
                ('date', models.CharField(default='Unknown', max_length=10)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conthorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Breeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datebreed', models.CharField(blank=True, max_length=10)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmhorse', to='horses.horse')),
                ('horse2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bmhorse2', to='horses.horse')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='repbreed', to='horses.repertory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
