# Generated by Django 3.2.4 on 2021-10-27 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0005_auto_20211027_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewormer',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='job',
            field=models.CharField(choices=[('farrier', 'Maréchal'), ('vet', 'Vétérinaire'), ('osteo', 'Osthéopathe'), ('inseminator', 'Inséminateur'), ('other', 'Autre'), ('rider', 'Cavalier professionnel'), ('provider', 'Fournisseur'), ('acup', 'Acupuncteur'), ('masseur', 'Masseur'), ('breeder', 'Eleveur'), ('teacher', 'Moniteur'), ('dentist', 'Dentiste')], default='other', max_length=30),
        ),
    ]
