# Generated by Django 3.2.4 on 2021-10-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0006_auto_20211027_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='datestart',
            field=models.DateField(blank=True),
        ),
    ]
