# Generated by Django 3.2.4 on 2021-10-27 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0008_alter_dewormer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, default='0'),
        ),
        migrations.AddField(
            model_name='temperature',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='datebreed',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='dentistry',
            name='date',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='dateend',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='realend',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='heats',
            name='dateend',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='heats',
            name='datestart',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='dateend',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='osteopathy',
            name='date',
            field=models.DateField(blank=True, default='Unknown'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='next',
            field=models.DateField(blank=True),
        ),
    ]
