# Generated by Django 3.2.4 on 2021-10-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0011_alter_horse_yearofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='horse',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
