# Generated by Django 3.2.4 on 2021-11-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0012_horse_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='horse',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
