# Generated by Django 3.2.4 on 2021-11-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0013_auto_20211101_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='picture',
            field=models.ImageField(blank=True, upload_to='horses'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profiles'),
        ),
    ]
