# Generated by Django 3.2.4 on 2021-11-02 20:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0014_auto_20211102_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profiles'), upload_to='profiles'),
        ),
    ]
