# Generated by Django 3.2.4 on 2021-11-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0018_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='yearofbirth',
            field=models.PositiveSmallIntegerField(blank=True, default=2021),
        ),
    ]
