# Generated by Django 3.2.4 on 2021-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0019_alter_horse_yearofbirth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horse',
            name='yearofbirth',
        ),
        migrations.AddField(
            model_name='horse',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
