# Generated by Django 3.2.4 on 2021-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0020_auto_20211104_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='age',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
