# Generated by Django 3.2.4 on 2021-11-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0022_horse_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='sex',
            field=models.CharField(choices=[('Jument', 'Jument'), ('Entier', 'Entier'), ('Hongre', 'Hongre'), ('Etalon', 'Etalon')], default='Hongre', max_length=6),
        ),
    ]
