# Generated by Django 3.2.4 on 2021-11-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0023_alter_horse_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='dam',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='damdam',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='damsire',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='sire',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='siredam',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='siresire',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='horse',
            name='tests',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
