# Generated by Django 3.2.4 on 2021-11-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0025_auto_20211107_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profiles', width_field=120),
        ),
    ]
