# Generated by Django 3.2.4 on 2021-11-08 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0031_alter_user_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='notes',
        ),
    ]
