# Generated by Django 3.2.4 on 2021-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0032_remove_vaccine_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='next',
            field=models.DateField(blank=True, null=True),
        ),
    ]
