# Generated by Django 3.2.4 on 2021-11-09 16:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0033_auto_20211109_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='datebreed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dentistry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dewormer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='dateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='datestart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='realend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heats',
            name='dateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='heats',
            name='datestart',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='dateend',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='osteopathy',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repertory',
            name='tab',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.CreateModel(
            name='Farriery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(blank=True, null=True)),
                ('farrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repfarr', to='horses.repertory')),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farrhorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farrowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
