# Generated by Django 3.2.4 on 2021-11-09 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0034_auto_20211109_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default='Unknown')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dateshorse', to='horses.horse')),
                ('other', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='repdate', to='horses.repertory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
