# Generated by Django 3.2.4 on 2021-11-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0036_auto_20211109_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repertory',
            name='tab',
            field=models.IntegerField(default=0),
        ),
    ]
