# Generated by Django 3.2.4 on 2021-11-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0038_alter_repertory_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='lot',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
