# Generated by Django 3.2.4 on 2021-11-11 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0039_inventory_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='temp',
            field=models.FloatField(default='37.5'),
        ),
    ]
