# Generated by Django 3.2.4 on 2021-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0040_auto_20211111_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repertory',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='repertory',
            name='lastname',
        ),
        migrations.AddField(
            model_name='repertory',
            name='name',
            field=models.CharField(default='Inconnu', max_length=40),
            preserve_default=False,
        ),
    ]
