# Generated by Django 3.2.4 on 2021-11-18 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0041_auto_20211113_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='reason',
            field=models.CharField(default='Non spécifié', max_length=300),
        ),
    ]
