# Generated by Django 3.2.4 on 2021-11-18 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0042_alter_dates_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repdate', to='horses.repertory'),
        ),
    ]
