# Generated by Django 3.2.4 on 2021-11-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0043_alter_dates_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dates',
            name='other',
            field=models.CharField(blank=True, default='Non spécifié', max_length=200),
            preserve_default=False,
        ),
    ]
