# Generated by Django 3.2.4 on 2021-11-22 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0045_auto_20211119_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breeding',
            name='datebreed',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='contest',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='dentistry',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='dewormer',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='farriery',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='datestart',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='heats',
            name='datestart',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='incident',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='osteopathy',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
