# Generated by Django 3.2.4 on 2021-11-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0046_auto_20211122_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farriery',
            name='farrier',
            field=models.CharField(blank=True, default='Non spécifié', max_length=200),
        ),
    ]
