# Generated by Django 3.2.4 on 2021-11-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0048_alter_farriery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farriery',
            name='farrier',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
    ]
