# Generated by Django 3.2.4 on 2021-11-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0049_alter_farriery_farrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='vet',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='horse2',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
        migrations.AlterField(
            model_name='breeding',
            name='person',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
        migrations.AlterField(
            model_name='dentistry',
            name='dentist',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='vet',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
        migrations.AlterField(
            model_name='osteopathy',
            name='osteo',
            field=models.CharField(default='Non spécifié', max_length=200),
        ),
    ]
