# Generated by Django 3.2.4 on 2021-11-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0050_auto_20211122_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewormer',
            name='nextdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
