# Generated by Django 3.2.4 on 2021-11-24 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0051_alter_dewormer_nextdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewormer',
            name='name',
            field=models.CharField(default='Non spécifié', max_length=30),
        ),
    ]
