# Generated by Django 3.2.4 on 2021-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0053_alter_repertory_nb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osteopathy',
            name='diagnostic',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='osteopathy',
            name='reeducation',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
