# Generated by Django 3.2.4 on 2021-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0055_alter_osteopathy_reeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='place',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
