# Generated by Django 3.2.4 on 2021-11-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0056_contest_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='diagnostic',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='prescription',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='incident',
            name='vet',
            field=models.CharField(default='Non spécifié', max_length=150),
        ),
    ]
