# Generated by Django 3.2.4 on 2021-11-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0058_auto_20211128_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='place',
            field=models.CharField(default='Non spécifié', max_length=80),
        ),
        migrations.AlterField(
            model_name='contest',
            name='result',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
