# Generated by Django 3.2.4 on 2021-12-01 20:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0060_remove_breeding_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeding',
            old_name='horse2',
            new_name='mare',
        ),
        migrations.CreateModel(
            name='Bred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stallion', models.CharField(default='Non spécifié', max_length=200)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('notes', models.CharField(blank=True, max_length=1000)),
                ('horse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmarehorse', to='horses.horse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bmareowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
