# Generated by Django 3.2.4 on 2021-12-01 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0061_auto_20211201_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breeding',
            old_name='datebreed',
            new_name='date',
        ),
    ]
