# Generated by Django 3.2.4 on 2021-12-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0062_rename_datebreed_breeding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='dateend',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='echo1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='echo2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='echo3',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='gestation',
            name='realend',
            field=models.DateField(null=True),
        ),
    ]
