# Generated by Django 3.2.4 on 2021-12-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0063_auto_20211204_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='notes',
            field=models.TextField(blank=True, max_length=4000),
        ),
    ]
