# Generated by Django 3.2.4 on 2021-12-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0064_alter_gestation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='dateend',
            field=models.DateField(default=datetime.datetime(2022, 11, 9, 20, 51, 15, 869985)),
        ),
    ]
