# Generated by Django 3.2.4 on 2021-12-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0065_alter_gestation_dateend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestation',
            name='dateend',
            field=models.DateField(null=True),
        ),
    ]
