# Generated by Django 3.2.4 on 2021-12-04 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0066_alter_gestation_dateend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestation',
            name='foal',
        ),
    ]
