# Generated by Django 3.2.4 on 2021-12-06 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0068_auto_20211205_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
