# Generated by Django 3.2.4 on 2021-12-06 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0069_auto_20211206_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created',
        ),
    ]
