# Generated by Django 3.2.4 on 2021-12-09 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0072_alter_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('tmp', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
