# Generated by Django 3.2.4 on 2021-12-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0073_tmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bred',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breeding',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dates',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dentistry',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dewormer',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farriery',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gestation',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heats',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='osteopathy',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='temperature',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
