# Generated by Django 3.2.4 on 2021-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0074_auto_20211210_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dewormer',
            old_name='notified',
            new_name='notified1',
        ),
        migrations.RenameField(
            model_name='vaccine',
            old_name='notified',
            new_name='notified1',
        ),
        migrations.AddField(
            model_name='dewormer',
            name='notified2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='notified2',
            field=models.BooleanField(default=False),
        ),
    ]
