# Generated by Django 3.2.4 on 2021-12-16 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0075_auto_20211210_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2021)]),
        ),
    ]
