# Generated by Django 3.2.4 on 2021-12-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0078_alter_horse_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(choices=[('Femme', 'horses\\static\\horses\x07vatars\\Historical-Cowgirl-icon.png'), ('Homme', 'horses\\static\\horses\x07vatars\\Historical-Cowboy-icon.png'), ('Aucun avatar', 'horses\\static\\horses\\grey.jpg')], max_length=300),
        ),
    ]
