# Generated by Django 3.2.4 on 2021-12-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0079_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(choices=[('Femme', 'Femme'), ('Homme', 'Homme'), ('Non spécifié', 'Non spécifié')], default='Non spécifié', max_length=15),
        ),
    ]
