# Generated by Django 3.2.4 on 2021-12-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horses', '0080_alter_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='picture',
            field=models.CharField(default='4', max_length=20),
        ),
    ]
