from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_f, name="login"),
    path("logout", views.logout_f, name="logout"),
    path("register", views.register, name="register"), 
    path("activate/<slug:uidb64>/<slug:token>/",  views.activate, name="activate"),   
    path("search/<int:id_user>/<str:context>", views.search, name="search"),
    path("yearview/<int:id_horse>/<int:year>/<str:context>", views.yearview, name="yearview"),
    path("profile/<int:id>", views.profile, name="profile"),   
    path("edituser/<int:id>", views.edituser, name="edituser"),
    path("editpassword/<int:id>", views.editpassword, name="editpassword"),
    path("deleteuser/<int:id>", views.deleteuser, name="deleteuser"),
    path("contacts", views.contacts, name="contacts"),
    path("contact/<int:id>", views.contact, name="contact"),
    path("erasecontact/<int:id>", views.deletecontact, name="deletecontact"),
    path("inventory", views.inventory, name="inventory"),
    path("pastinventory/<int:id>/<int:context>", views.pastinventory, name="pastinventory"),
    path("edititem/<int:id>", views.edititem, name="edititem"),
    path("edititem/e-s/<int:id>", views.edites, name="edites"),
    path("horses", views.horses, name="myhorses"),
    path("horse/<int:id>", views.horse, name="horse"),
    path("deletehorse/<int:id>", views.delete, name="delete"),   
    path("edithorse/<int:id>", views.edithorse, name="edithorse"),
    path("edithorsepic/<int:id>", views.edithorsepic, name="edithorsepic"),
    path("editnotes/<int:id>", views.editnotes, name="editnotes"),
    path("newvax/<int:id>", views.newvax, name="newvax"),
    path("editvax/<int:id>", views.editvax, name="editvax"),
    path("newdate/<int:id>", views.newdate, name="newdate"),
    path("editdate/<int:id>", views.editdate, name="editdate"),
    path("farriery/<int:id>", views.farriery, name="farriery"),
    path("editfarriery/<int:id>", views.editfarriery, name="editfarriery"),
    path("dewormer/<int:id>", views.dewormer, name="dewormer"),
    path("editdewormer/<int:id>", views.editdewormer, name="editdewormer"),
    path("dentistry/<int:id>", views.dentistry, name="dentistry"),
    path("editdentistry/<int:id>", views.editdentistry, name="editdentistry"),
    path("editpedigree/<int:id>", views.editpedigree, name="editpedigree"),
    path("osteopathy/<int:id>", views.osteopathy, name="osteopathy"),
    path("editosteopathy/<int:id>", views.editosteopathy, name="editosteopathy"),
    path("contest/<int:id>", views.contest, name="contest"),
    path("editcontest/<int:id>", views.editcontest, name="editcontest"),
    path("incident/<int:id>", views.incident, name="incident"),
    path("editincident/<int:id>", views.editincident, name="editincident"),
    path("breeding/<int:id>", views.breeding, name="breeding"),
    path("editbreeding/<int:id>", views.editbreeding, name="editbreeding"),
    path("bred/<int:id>", views.bred, name="bred"),
    path("editbred/<int:id>", views.editbred, name="editbred"),
    path("heat/<int:id>", views.heat, name="heat"),
    path("editheat/<int:id>", views.editheat, name="editheat"),
    path("gestation/<int:id>", views.gestation, name="gestation"),
    path("editgestation/<int:id>", views.editgestation, name="editgestation"),
    path("contact-us", views.contactus, name="contactus"),
    path("help", views.help, name="help"),
    path("politique-de-confidentialite", views.politiquedeconf, name="politiquedeconf"),
    path("confirmationemail/<int:id>", views.emailconfnew, name="emailconfnew"),
    path("resetpassword/", views.resetpassword, name="resetpassword"),
    path("setnewpassword/<slug:uidb64>/<slug:token>/", views.setnewpassword, name="setnewpassword"),
    path("passwordset/<int:id>", views.confirmnewpassword, name="confirmnewpassword"),
    path("cleanup/", views.cleanup, name="cleanup"),
    path("notifications", views.notifications, name="notifs")
    
]

